### ISSUE TITLE
Think about and converge on format for online mini-workshops

### ISSUE THREAD

**Issue by DaniJonesOcean** [SOOS-OSD/General#3]
The SOOS OSD Capability Working Group aims to "facilitate the design of a comprehensive and multi-disciplinary observing system for the Southern Ocean by analyzing methods, providing guidance for optimizing observational strategies and seeking to enhance collaboration and instigate discussions on this important topic". This can only happen if we have a community roughly "pointing in the same direction". 

One way to help establish and maintain such a community is to have regular online mini-workshops. @YosrAmmar and I had a discussion about the possible format of these workshops. Because there are so many other good webinar series out there, we don't want to replicate that same format - we'd like to do something a little bit different. I don't think that we need another standard 45-15 web series, with 45 minutes of a talk and a short 15 minute discussion during which just a couple people ask questions. That format won't help us make progress on the SOOS OSD terms of reference. 

I was inspired by the format of the Southern Ocean session at EGU2021, which was held entirely online. It was really engaging and effective. This session consisted of three parts:
1. Short formal talks during the official EGU session (the usual)
2. An unofficial "plenary discussion" section with topics/questions outlined in advance
3. An unofficial and informal chat, in a more social space
I'd like to draw on this format for our mini-workshops, with lot of time for a loosely structured plenary discussion. 

Here are some specifics we discussed:
- Monthly format, aiming to start in October, with three sections: 
-- **Stage-setting:** a 15 minute talk by an invited speaker, on a specific invited topic
-- **Plenary discussion:** a 30 minute discussion, with topics/questions specified in advance
-- **Informal chat:** 15+ minute more informal chat, hosted by SOOS-OSD members
- We'll ask speakers to talk about their work as it relates to our terms of reference
- We'll ask speakers if they'd like us to send around materials beforehand (e.g. papers, other long talks)

We can advertise these sessions using the forthcoming SOOS-OSD mailing list, twitter, individual email lists, and so on. 

@YosrAmmar, please feel free to add anything I've missed from our chat! And @llenain, it would be good to hear your thoughts as well.   : ) 

I'm excited about these! I think they have great potential.

**Comment by DanJonesOcean** [comment]
Reformat this issue and use GitHub to have the discussion

**Comment by YosrAmmar** [comment]
Thanks Dan for the great summary, I think you have mentioned everything we talked about. Sounds very exciting, looking forward to start.

**Comment by DaniJonesOcean** [comment]
We won't manage an October start for these, but we might be okay for a January start.

It seems like we're probably happy with this format. I have some ideas for speakers, but I'd also like to get input from our community. One idea would be to ask the mailing list members for ideas for speakers, topics/questions, to gauge where the interest lies right now. 

I'll draft something up.

**Comment by DaniJonesOcean** [comment]
Okay, we've pretty much converged on a format between us. Closing this issue now
